[package]
name = "blockchain"
version = "0.1.0"
authors = ["Miguel Berrio <miguelberrio91@gmail.com>, Dimitrij Vogt <divogt@live.de>"]

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
ring = "*"
